{
  "openapi": "3.0.0",
  "info": {
    "title": "Base API V1",
    "version": "v1"
  },
  "paths": {
    "/api/v1/medications/new": {
      "post": {
        "summary": "new medication",
        "tags": [
          "Medications"
        ],
        "description": "Creates a new medication record",
        "security": [
          {
            "bearer_auth": []
          }
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "success"
          },
          "401": {
            "description": "authentication failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/bad_credentials"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/new_medication"
              }
            }
          }
        }
      }
    },
    "/api/v1/medications/meds": {
      "get": {
        "summary": "meds medication",
        "tags": [
          "Medications"
        ],
        "description": "Retrieves user's stored medications",
        "security": [
          {
            "bearer_auth": []
          }
        ],
        "responses": {
          "200": {
            "description": "successful"
          },
          "400": {
            "description": "no meds found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/no_meds"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/medications/delete": {
      "delete": {
        "summary": "delete medication",
        "tags": [
          "Medications"
        ],
        "description": "Retrieves user's stored medications",
        "security": [
          {
            "bearer_auth": []
          }
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "successful"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/delete_medication"
              }
            }
          }
        }
      }
    },
    "/api/v1/medications/edit": {
      "patch": {
        "summary": "edit medication",
        "tags": [
          "Medications"
        ],
        "description": "Edits a stored medication",
        "security": [
          {
            "bearer_auth": []
          }
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "successful"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/edit_medication"
              }
            }
          }
        }
      }
    },
    "/api/v1/users/login": {
      "post": {
        "summary": "login user",
        "tags": [
          "Users"
        ],
        "description": "Logs in a user",
        "parameters": [],
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "success": true,
                    "payload": {
                      "id": 88722,
                      "email": "val.beer@schmidt-schroeder.io",
                      "first_name": "Chas",
                      "last_name": "MacGyver",
                      "name": "Chas MacGyver",
                      "token": {
                        "id": 59329,
                        "created_at": "2023-04-21 19:15:23 UTC",
                        "expiry": "2023-04-28 19:15:23 UTC",
                        "ip": null,
                        "revocation_date": null,
                        "updated_at": "2023-04-21 19:15:23 UTC",
                        "user_id": 88722,
                        "value": "16xL8cofbzt9qKcacJ754tyqQC6w2WpgkU"
                      }
                    },
                    "status": 200
                  }
                }
              }
            }
          },
          "401": {
            "description": "Error: Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/unauthenticated_user"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/login_user"
              }
            }
          }
        }
      }
    },
    "/api/v1/users/logout": {
      "delete": {
        "summary": "logout user",
        "tags": [
          "Users"
        ],
        "description": "Logs out a user",
        "security": [
          {
            "bearer_auth": []
          }
        ],
        "responses": {
          "200": {
            "description": "logged out user",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/logout_user"
                }
              }
            }
          },
          "401": {
            "description": "authentication failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/bad_credentials"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/users/me": {
      "get": {
        "summary": "me user",
        "tags": [
          "Users"
        ],
        "description": "Display the current user",
        "security": [
          {
            "bearer_auth": []
          }
        ],
        "responses": {
          "200": {
            "description": "user profile",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "payload": {
                      "id": 88722,
                      "email": "val.beer@schmidt-schroeder.io",
                      "first_name": "Chas",
                      "last_name": "MacGyver",
                      "name": "Chas MacGyver"
                    },
                    "status": 200
                  }
                }
              }
            }
          },
          "401": {
            "description": "authentication failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/bad_credentials"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/users/create": {
      "post": {
        "summary": "create user",
        "tags": [
          "Users"
        ],
        "description": "Create a new user",
        "parameters": [],
        "responses": {
          "201": {
            "description": "user created",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "success": true,
                    "payload": {
                      "id": 88722,
                      "email": "val.beer@schmidt-schroeder.io",
                      "first_name": "Chas",
                      "last_name": "MacGyver",
                      "name": "Chas MacGyver"
                    },
                    "status": 201
                  }
                }
              }
            }
          },
          "400": {
            "description": "invalid request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error_saving_user"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/create_user"
              }
            }
          }
        }
      }
    }
  },
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "components": {
    "securitySchemes": {
      "bearer_auth": {
        "type": "http",
        "scheme": "bearer",
        "bearer_format": "string"
      }
    },
    "schemas": {
      "create_user": {
        "type": "object",
        "properties": {
          "first_name": {
            "type": "string",
            "nullable": false
          },
          "last_name": {
            "type": "string",
            "nullable": false
          },
          "email": {
            "type": "string",
            "nullable": false
          },
          "password": {
            "type": "string",
            "nullable": false
          },
          "password_confirmation": {
            "type": "string",
            "nullable": false
          }
        },
        "required": [
          "first_name",
          "last_name",
          "email",
          "password",
          "password_confirmation"
        ]
      },
      "login_user_payload": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "payload": {
            "type": "object",
            "properties": {
              "user": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer",
                    "example": 52198
                  },
                  "email": {
                    "type": "string",
                    "example": "kayleigh@koelpin.biz"
                  },
                  "first_name": {
                    "type": "string",
                    "example": "Deanne"
                  },
                  "last_name": {
                    "type": "string",
                    "example": "Lubowitz"
                  },
                  "name": {
                    "type": "string",
                    "example": "Deanne Lubowitz"
                  },
                  "token": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer",
                        "example": 50763
                      },
                      "created_at": {
                        "type": "string",
                        "example": "2023-04-21 19:15:23 UTC"
                      },
                      "expiry": {
                        "type": "string",
                        "example": "2023-04-28 19:15:23 UTC"
                      },
                      "ip": {
                        "type": "any",
                        "example": null
                      },
                      "revocation_date": {
                        "type": "any",
                        "example": null
                      },
                      "updated_at": {
                        "type": "string",
                        "example": "2023-04-21 19:15:23 UTC"
                      },
                      "user_id": {
                        "type": "integer",
                        "example": 52198
                      },
                      "value": {
                        "type": "string",
                        "example": "148ePsUXygG6NUzretJGyVmM6FvstvoK3H"
                      }
                    }
                  }
                }
              }
            }
          },
          "token": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer",
                "example": 50763
              },
              "created_at": {
                "type": "string",
                "example": "2023-04-21 19:15:23 UTC"
              },
              "expiry": {
                "type": "string",
                "example": "2023-04-28 19:15:23 UTC"
              },
              "ip": {
                "type": "any",
                "example": null
              },
              "revocation_date": {
                "type": "any",
                "example": null
              },
              "updated_at": {
                "type": "string",
                "example": "2023-04-21 19:15:23 UTC"
              },
              "user_id": {
                "type": "integer",
                "example": 52198
              },
              "value": {
                "type": "string",
                "example": "148ePsUXygG6NUzretJGyVmM6FvstvoK3H"
              }
            }
          },
          "status": {
            "type": "integer",
            "example": 200
          }
        }
      },
      "unauthenticated_user": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": false
          },
          "errors": {
            "type": "string",
            "example": "User not authenticated"
          },
          "status": {
            "type": "integer",
            "example": 401
          }
        }
      },
      "logout_user": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "payload": {
            "type": "string",
            "example": "You have been logged out"
          }
        }
      },
      "login_user": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "required": true,
            "description": "email required"
          },
          "password": {
            "type": "string",
            "required": true,
            "description": "password required"
          }
        },
        "required": [
          "email",
          "password"
        ]
      },
      "bad_credentials": {
        "type": "object",
        "properties": {
          "error": {
            "type": "string",
            "example": "Bad Credentials"
          },
          "status": {
            "type": "integer",
            "example": 401
          }
        }
      },
      "me": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "payload": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer",
                "example": 52198
              },
              "email": {
                "type": "string",
                "example": "kayleigh@koelpin.biz"
              },
              "first_name": {
                "type": "string",
                "example": "Deanne"
              },
              "last_name": {
                "type": "string",
                "example": "Lubowitz"
              },
              "name": {
                "type": "string",
                "example": "Deanne Lubowitz"
              }
            }
          }
        }
      },
      "create_user_payload": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "payload": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer",
                "example": 52198
              },
              "email": {
                "type": "string",
                "example": "kayleigh@koelpin.biz"
              },
              "first_name": {
                "type": "string",
                "example": "Deanne"
              },
              "last_name": {
                "type": "string",
                "example": "Lubowitz"
              },
              "name": {
                "type": "string",
                "example": "Deanne Lubowitz"
              }
            }
          }
        }
      },
      "error_saving_user": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": false
          },
          "errors": {
            "type": "string",
            "example": "There was a problem creating a new user"
          },
          "status": {
            "type": "integer",
            "example": 400
          }
        }
      },
      "no_meds": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": false
          },
          "errors": {
            "type": "string",
            "example": "no medications found"
          },
          "status": {
            "type": "integer",
            "example": 400
          }
        }
      },
      "new_medication": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "nullable": false
          },
          "dosage": {
            "type": "string",
            "nullable": true
          },
          "frequency": {
            "type": "string",
            "nullable": true
          },
          "date": {
            "type": "string",
            "nullable": true
          },
          "day": {
            "type": "string",
            "nullable": true
          },
          "benefits": {
            "type": "string",
            "nullable": true
          },
          "side_effects": {
            "type": "string",
            "nullable": true
          },
          "start_date": {
            "type": "string",
            "nullable": true
          },
          "stop_date": {
            "type": "string",
            "nullable": true
          },
          "reason_stopped": {
            "type": "string",
            "nullable": true
          },
          "is_current": {
            "type": "boolean",
            "nullable": false
          },
          "morning": {
            "type": "boolean",
            "nullable": true
          },
          "midday": {
            "type": "boolean",
            "nullable": true
          },
          "evening": {
            "type": "boolean",
            "nullable": true
          },
          "night": {
            "type": "boolean",
            "nullable": true
          }
        }
      },
      "new_medication_payload": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "payload": {
            "id": {
              "type": "integer"
            },
            "name": {
              "type": "string"
            },
            "dosage": {
              "type": "string"
            },
            "frequency": {
              "type": "string"
            },
            "date": {
              "type": "string"
            },
            "day": {
              "type": "string"
            },
            "benefits": {
              "type": "string"
            },
            "side_effects": {
              "type": "string"
            },
            "start_date": {
              "type": "string"
            },
            "stop_date": {
              "type": "string"
            },
            "reason_stopped": {
              "type": "string"
            },
            "is_current": {
              "type": "boolean"
            },
            "created_at": {
              "type": "string"
            },
            "updated_at": {
              "type": "string"
            },
            "morning": {
              "type": "boolean"
            },
            "midday": {
              "type": "boolean"
            },
            "evening": {
              "type": "boolean"
            },
            "night": {
              "type": "boolean"
            },
            "user_id": {
              "type": "integer"
            }
          }
        }
      },
      "meds_medication": {
        "type": "string",
        "properties": {
          "user_id": {
            "type": "integer",
            "example": 52198
          }
        }
      },
      "meds_medication_payload": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "payload": {
            "id": {
              "type": "integer"
            },
            "name": {
              "type": "string"
            },
            "dosage": {
              "type": "string"
            },
            "frequency": {
              "type": "string"
            },
            "date": {
              "type": "string"
            },
            "day": {
              "type": "string"
            },
            "benefits": {
              "type": "string"
            },
            "side_effects": {
              "type": "string"
            },
            "start_date": {
              "type": "string"
            },
            "stop_date": {
              "type": "string"
            },
            "reason_stopped": {
              "type": "string"
            },
            "is_current": {
              "type": "boolean"
            },
            "created_at": {
              "type": "string"
            },
            "updated_at": {
              "type": "string"
            },
            "morning": {
              "type": "boolean"
            },
            "midday": {
              "type": "boolean"
            },
            "evening": {
              "type": "boolean"
            },
            "night": {
              "type": "boolean"
            },
            "user_id": {
              "type": "integer"
            }
          }
        }
      },
      "delete_medication": {
        "type": "object",
        "properties": {
          "user_id": {
            "type": "integer"
          },
          "med_id": {
            "type": "integer"
          }
        }
      },
      "user_id": {
        "type": "object",
        "properties": {
          "user_id": {
            "type": "integer",
            "example": 52198
          }
        }
      },
      "edit_medication": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "nullable": false
          },
          "dosage": {
            "type": "string",
            "nullable": true
          },
          "frequency": {
            "type": "string",
            "nullable": true
          },
          "date": {
            "type": "string",
            "nullable": true
          },
          "day": {
            "type": "string",
            "nullable": true
          },
          "benefits": {
            "type": "string",
            "nullable": true
          },
          "side_effects": {
            "type": "string",
            "nullable": true
          },
          "start_date": {
            "type": "string",
            "nullable": true
          },
          "stop_date": {
            "type": "string",
            "nullable": true
          },
          "reason_stopped": {
            "type": "string",
            "nullable": true
          },
          "is_current": {
            "type": "boolean",
            "nullable": false
          },
          "morning": {
            "type": "boolean",
            "nullable": true
          },
          "midday": {
            "type": "boolean",
            "nullable": true
          },
          "evening": {
            "type": "boolean",
            "nullable": true
          },
          "night": {
            "type": "boolean",
            "nullable": true
          }
        }
      }
    }
  }
}